window.cities = [
    {
        countryName: "Afghanistan",
        capitalName: "Kabul",
        capitalLatitude: "34,51666667",
        capitalLongitude: "69,183333",
        countryCode: "AF",
        continentName: "Asia",
    },
    {
        countryName: "Aland Islands",
        capitalName: "Mariehamn",
        capitalLatitude: "60,116667",
        capitalLongitude: "19,9",
        countryCode: "AX",
        continentName: "Europe",
    },
    {
        countryName: "Albania",
        capitalName: "Tirana",
        capitalLatitude: "41,31666667",
        capitalLongitude: "19,816667",
        countryCode: "AL",
        continentName: "Europe",
    },
    {
        countryName: "Algeria",
        capitalName: "Algiers",
        capitalLatitude: "36,75",
        capitalLongitude: "3,05",
        countryCode: "DZ",
        continentName: "Africa",
    },
    {
        countryName: "American Samoa",
        capitalName: "Pago Pago",
        capitalLatitude: "-14,26666667",
        capitalLongitude: "-170,7",
        countryCode: "AS",
        continentName: "Australia",
    },
    {
        countryName: "Andorra",
        capitalName: "Andorra la Vella",
        capitalLatitude: "42,5",
        capitalLongitude: "1,516667",
        countryCode: "AD",
        continentName: "Europe",
    },
    {
        countryName: "Angola",
        capitalName: "Luanda",
        capitalLatitude: "-8,833333333",
        capitalLongitude: "13,216667",
        countryCode: "AO",
        continentName: "Africa",
    },
    {
        countryName: "Anguilla",
        capitalName: "The Valley",
        capitalLatitude: "18,21666667",
        capitalLongitude: "-63,05",
        countryCode: "AI",
        continentName: "North America",
    },
    {
        countryName: "Antigua and Barbuda",
        capitalName: "Saint John�s",
        capitalLatitude: "17,11666667",
        capitalLongitude: "-61,85",
        countryCode: "AG",
        continentName: "North America",
    },
    {
        countryName: "Argentina",
        capitalName: "Buenos Aires",
        capitalLatitude: "-34,58333333",
        capitalLongitude: "-58,666667",
        countryCode: "AR",
        continentName: "South America",
    },
    {
        countryName: "Armenia",
        capitalName: "Yerevan",
        capitalLatitude: "40,16666667",
        capitalLongitude: "44,5",
        countryCode: "AM",
        continentName: "Europe",
    },
    {
        countryName: "Aruba",
        capitalName: "Oranjestad",
        capitalLatitude: "12,51666667",
        capitalLongitude: "-70,033333",
        countryCode: "AW",
        continentName: "North America",
    },
    {
        countryName: "Australia",
        capitalName: "Canberra",
        capitalLatitude: "-35,26666667",
        capitalLongitude: "149,133333",
        countryCode: "AU",
        continentName: "Australia",
    },
    {
        countryName: "Austria",
        capitalName: "Vienna",
        capitalLatitude: "48,2",
        capitalLongitude: "16,366667",
        countryCode: "AT",
        continentName: "Europe",
    },
    {
        countryName: "Azerbaijan",
        capitalName: "Baku",
        capitalLatitude: "40,38333333",
        capitalLongitude: "49,866667",
        countryCode: "AZ",
        continentName: "Europe",
    },
    {
        countryName: "Bahamas",
        capitalName: "Nassau",
        capitalLatitude: "25,08333333",
        capitalLongitude: "-77,35",
        countryCode: "BS",
        continentName: "North America",
    },
    {
        countryName: "Bahrain",
        capitalName: "Manama",
        capitalLatitude: "26,23333333",
        capitalLongitude: "50,566667",
        countryCode: "BH",
        continentName: "Asia",
    },
    {
        countryName: "Bangladesh",
        capitalName: "Dhaka",
        capitalLatitude: "23,71666667",
        capitalLongitude: "90,4",
        countryCode: "BD",
        continentName: "Asia",
    },
    {
        countryName: "Barbados",
        capitalName: "Bridgetown",
        capitalLatitude: "13,1",
        capitalLongitude: "-59,616667",
        countryCode: "BB",
        continentName: "North America",
    },
    {
        countryName: "Belarus",
        capitalName: "Minsk",
        capitalLatitude: "53,9",
        capitalLongitude: "27,566667",
        countryCode: "BY",
        continentName: "Europe",
    },
    {
        countryName: "Belgium",
        capitalName: "Brussels",
        capitalLatitude: "50,83333333",
        capitalLongitude: "4,333333",
        countryCode: "BE",
        continentName: "Europe",
    },
    {
        countryName: "Belize",
        capitalName: "Belmopan",
        capitalLatitude: "17,25",
        capitalLongitude: "-88,766667",
        countryCode: "BZ",
        continentName: "Central America",
    },
    {
        countryName: "Benin",
        capitalName: "Porto-Novo",
        capitalLatitude: "6,483333333",
        capitalLongitude: "2,616667",
        countryCode: "BJ",
        continentName: "Africa",
    },
    {
        countryName: "Bermuda",
        capitalName: "Hamilton",
        capitalLatitude: "32,28333333",
        capitalLongitude: "-64,783333",
        countryCode: "BM",
        continentName: "North America",
    },
    {
        countryName: "Bhutan",
        capitalName: "Thimphu",
        capitalLatitude: "27,46666667",
        capitalLongitude: "89,633333",
        countryCode: "BT",
        continentName: "Asia",
    },
    {
        countryName: "Bolivia",
        capitalName: "La Paz",
        capitalLatitude: "-16,5",
        capitalLongitude: "-68,15",
        countryCode: "BO",
        continentName: "South America",
    },
    {
        countryName: "Bosnia and Herzegovina",
        capitalName: "Sarajevo",
        capitalLatitude: "43,86666667",
        capitalLongitude: "18,416667",
        countryCode: "BA",
        continentName: "Europe",
    },
    {
        countryName: "Botswana",
        capitalName: "Gaborone",
        capitalLatitude: "-24,63333333",
        capitalLongitude: "25,9",
        countryCode: "BW",
        continentName: "Africa",
    },
    {
        countryName: "Brazil",
        capitalName: "Brasilia",
        capitalLatitude: "-15,78333333",
        capitalLongitude: "-47,916667",
        countryCode: "BR",
        continentName: "South America",
    },
    {
        countryName: "British Indian Ocean Territory",
        capitalName: "Diego Garcia",
        capitalLatitude: "-7,3",
        capitalLongitude: "72,4",
        countryCode: "IO",
        continentName: "Africa",
    },
    {
        countryName: "British Virgin Islands",
        capitalName: "Road Town",
        capitalLatitude: "18,41666667",
        capitalLongitude: "-64,616667",
        countryCode: "VG",
        continentName: "North America",
    },
    {
        countryName: "Brunei Darussalam",
        capitalName: "Bandar Seri Begawan",
        capitalLatitude: "4,883333333",
        capitalLongitude: "114,933333",
        countryCode: "BN",
        continentName: "Asia",
    },
    {
        countryName: "Bulgaria",
        capitalName: "Sofia",
        capitalLatitude: "42,68333333",
        capitalLongitude: "23,316667",
        countryCode: "BG",
        continentName: "Europe",
    },
    {
        countryName: "Burkina Faso",
        capitalName: "Ouagadougou",
        capitalLatitude: "12,36666667",
        capitalLongitude: "-1,516667",
        countryCode: "BF",
        continentName: "Africa",
    },
    {
        countryName: "Burundi",
        capitalName: "Bujumbura",
        capitalLatitude: "-3,366666667",
        capitalLongitude: "29,35",
        countryCode: "BI",
        continentName: "Africa",
    },
    {
        countryName: "Cambodia",
        capitalName: "Phnom Penh",
        capitalLatitude: "11,55",
        capitalLongitude: "104,916667",
        countryCode: "KH",
        continentName: "Asia",
    },
    {
        countryName: "Cameroon",
        capitalName: "Yaounde",
        capitalLatitude: "3,866666667",
        capitalLongitude: "11,516667",
        countryCode: "CM",
        continentName: "Africa",
    },
    {
        countryName: "Canada",
        capitalName: "Ottawa",
        capitalLatitude: "45,41666667",
        capitalLongitude: "-75,7",
        countryCode: "CA",
        continentName: "Central America",
    },
    {
        countryName: "Cape Verde",
        capitalName: "Praia",
        capitalLatitude: "14,91666667",
        capitalLongitude: "-23,516667",
        countryCode: "CV",
        continentName: "Africa",
    },
    {
        countryName: "Cayman Islands",
        capitalName: "George Town",
        capitalLatitude: "19,3",
        capitalLongitude: "-81,383333",
        countryCode: "KY",
        continentName: "North America",
    },
    {
        countryName: "Central African Republic",
        capitalName: "Bangui",
        capitalLatitude: "4,366666667",
        capitalLongitude: "18,583333",
        countryCode: "CF",
        continentName: "Africa",
    },
    {
        countryName: "Chad",
        capitalName: "N�Djamena",
        capitalLatitude: "12,1",
        capitalLongitude: "15,033333",
        countryCode: "TD",
        continentName: "Africa",
    },
    {
        countryName: "Chile",
        capitalName: "Santiago",
        capitalLatitude: "-33,45",
        capitalLongitude: "-70,666667",
        countryCode: "CL",
        continentName: "South America",
    },
    {
        countryName: "China",
        capitalName: "Beijing",
        capitalLatitude: "39,91666667",
        capitalLongitude: "116,383333",
        countryCode: "CN",
        continentName: "Asia",
    },
    {
        countryName: "Christmas Island",
        capitalName: "The Settlement",
        capitalLatitude: "-10,41666667",
        capitalLongitude: "105,716667",
        countryCode: "CX",
        continentName: "Australia",
    },
    {
        countryName: "Cocos Islands",
        capitalName: "West Island",
        capitalLatitude: "-12,16666667",
        capitalLongitude: "96,833333",
        countryCode: "CC",
        continentName: "Australia",
    },
    {
        countryName: "Colombia",
        capitalName: "Bogota",
        capitalLatitude: "4,6",
        capitalLongitude: "-74,083333",
        countryCode: "CO",
        continentName: "South America",
    },
    {
        countryName: "Comoros",
        capitalName: "Moroni",
        capitalLatitude: "-11,7",
        capitalLongitude: "43,233333",
        countryCode: "KM",
        continentName: "Africa",
    },
    {
        countryName: "Cook Islands",
        capitalName: "Avarua",
        capitalLatitude: "-21,2",
        capitalLongitude: "-159,766667",
        countryCode: "CK",
        continentName: "Australia",
    },
    {
        countryName: "Costa Rica",
        capitalName: "San Jose",
        capitalLatitude: "9,933333333",
        capitalLongitude: "-84,083333",
        countryCode: "CR",
        continentName: "Central America",
    },
    {
        countryName: "Cote d�Ivoire",
        capitalName: "Yamoussoukro",
        capitalLatitude: "6,816666667",
        capitalLongitude: "-5,266667",
        countryCode: "CI",
        continentName: "Africa",
    },
    {
        countryName: "Croatia",
        capitalName: "Zagreb",
        capitalLatitude: "45,8",
        capitalLongitude: "16",
        countryCode: "HR",
        continentName: "Europe",
    },
    {
        countryName: "Cuba",
        capitalName: "Havana",
        capitalLatitude: "23,11666667",
        capitalLongitude: "-82,35",
        countryCode: "CU",
        continentName: "North America",
    },
    {
        countryName: "Curaçao",
        capitalName: "Willemstad",
        capitalLatitude: "12,1",
        capitalLongitude: "-68,916667",
        countryCode: "CW",
        continentName: "North America",
    },
    {
        countryName: "Cyprus",
        capitalName: "Nicosia",
        capitalLatitude: "35,16666667",
        capitalLongitude: "33,366667",
        countryCode: "CY",
        continentName: "Europe",
    },
    {
        countryName: "Czech Republic",
        capitalName: "Prague",
        capitalLatitude: "50,08333333",
        capitalLongitude: "14,466667",
        countryCode: "CZ",
        continentName: "Europe",
    },
    {
        countryName: "Democratic Republic of the Congo",
        capitalName: "Kinshasa",
        capitalLatitude: "-4,316666667",
        capitalLongitude: "15,3",
        countryCode: "CD",
        continentName: "Africa",
    },
    {
        countryName: "Denmark",
        capitalName: "Copenhagen",
        capitalLatitude: "55,66666667",
        capitalLongitude: "12,583333",
        countryCode: "DK",
        continentName: "Europe",
    },
    {
        countryName: "Djibouti",
        capitalName: "Djibouti",
        capitalLatitude: "11,58333333",
        capitalLongitude: "43,15",
        countryCode: "DJ",
        continentName: "Africa",
    },
    {
        countryName: "Dominica",
        capitalName: "Roseau",
        capitalLatitude: "15,3",
        capitalLongitude: "-61,4",
        countryCode: "DM",
        continentName: "North America",
    },
    {
        countryName: "Dominican Republic",
        capitalName: "Santo Domingo",
        capitalLatitude: "18,46666667",
        capitalLongitude: "-69,9",
        countryCode: "DO",
        continentName: "North America",
    },
    {
        countryName: "Ecuador",
        capitalName: "Quito",
        capitalLatitude: "-0,216666667",
        capitalLongitude: "-78,5",
        countryCode: "EC",
        continentName: "South America",
    },
    {
        countryName: "Egypt",
        capitalName: "Cairo",
        capitalLatitude: "30,05",
        capitalLongitude: "31,25",
        countryCode: "EG",
        continentName: "Africa",
    },
    {
        countryName: "El Salvador",
        capitalName: "San Salvador",
        capitalLatitude: "13,7",
        capitalLongitude: "-89,2",
        countryCode: "SV",
        continentName: "Central America",
    },
    {
        countryName: "Equatorial Guinea",
        capitalName: "Malabo",
        capitalLatitude: "3,75",
        capitalLongitude: "8,783333",
        countryCode: "GQ",
        continentName: "Africa",
    },
    {
        countryName: "Eritrea",
        capitalName: "Asmara",
        capitalLatitude: "15,33333333",
        capitalLongitude: "38,933333",
        countryCode: "ER",
        continentName: "Africa",
    },
    {
        countryName: "Estonia",
        capitalName: "Tallinn",
        capitalLatitude: "59,43333333",
        capitalLongitude: "24,716667",
        countryCode: "EE",
        continentName: "Europe",
    },
    {
        countryName: "Ethiopia",
        capitalName: "Addis Ababa",
        capitalLatitude: "9,033333333",
        capitalLongitude: "38,7",
        countryCode: "ET",
        continentName: "Africa",
    },
    {
        countryName: "Falkland Islands",
        capitalName: "Stanley",
        capitalLatitude: "-51,7",
        capitalLongitude: "-57,85",
        countryCode: "FK",
        continentName: "South America",
    },
    {
        countryName: "Faroe Islands",
        capitalName: "Torshavn",
        capitalLatitude: "62",
        capitalLongitude: "-6,766667",
        countryCode: "FO",
        continentName: "Europe",
    },
    {
        countryName: "Federated States of Micronesia",
        capitalName: "Palikir",
        capitalLatitude: "6,916666667",
        capitalLongitude: "158,15",
        countryCode: "FM",
        continentName: "Australia",
    },
    {
        countryName: "Fiji",
        capitalName: "Suva",
        capitalLatitude: "-18,13333333",
        capitalLongitude: "178,416667",
        countryCode: "FJ",
        continentName: "Australia",
    },
    {
        countryName: "Finland",
        capitalName: "Helsinki",
        capitalLatitude: "60,16666667",
        capitalLongitude: "24,933333",
        countryCode: "FI",
        continentName: "Europe",
    },
    {
        countryName: "France",
        capitalName: "Paris",
        capitalLatitude: "48,86666667",
        capitalLongitude: "2,333333",
        countryCode: "FR",
        continentName: "Europe",
    },
    {
        countryName: "French Polynesia",
        capitalName: "Papeete",
        capitalLatitude: "-17,53333333",
        capitalLongitude: "-149,566667",
        countryCode: "PF",
        continentName: "Australia",
    },
    {
        countryName: "French Southern and Antarctic Lands",
        capitalName: "Port-aux-Francais",
        capitalLatitude: "-49,35",
        capitalLongitude: "70,216667",
        countryCode: "TF",
        continentName: "Antarctica",
    },
    {
        countryName: "Gabon",
        capitalName: "Libreville",
        capitalLatitude: "0,383333333",
        capitalLongitude: "9,45",
        countryCode: "GA",
        continentName: "Africa",
    },
    {
        countryName: "Georgia",
        capitalName: "Tbilisi",
        capitalLatitude: "41,68333333",
        capitalLongitude: "44,833333",
        countryCode: "GE",
        continentName: "Europe",
    },
    {
        countryName: "Germany",
        capitalName: "Berlin",
        capitalLatitude: "52,51666667",
        capitalLongitude: "13,4",
        countryCode: "DE",
        continentName: "Europe",
    },
    {
        countryName: "Ghana",
        capitalName: "Accra",
        capitalLatitude: "5,55",
        capitalLongitude: "-0,216667",
        countryCode: "GH",
        continentName: "Africa",
    },
    {
        countryName: "Gibraltar",
        capitalName: "Gibraltar",
        capitalLatitude: "36,13333333",
        capitalLongitude: "-5,35",
        countryCode: "GI",
        continentName: "Europe",
    },
    {
        countryName: "Greece",
        capitalName: "Athens",
        capitalLatitude: "37,98333333",
        capitalLongitude: "23,733333",
        countryCode: "GR",
        continentName: "Europe",
    },
    {
        countryName: "Greenland",
        capitalName: "Nuuk",
        capitalLatitude: "64,18333333",
        capitalLongitude: "-51,75",
        countryCode: "GL",
        continentName: "Central America",
    },
    {
        countryName: "Grenada",
        capitalName: "Saint George�s",
        capitalLatitude: "12,05",
        capitalLongitude: "-61,75",
        countryCode: "GD",
        continentName: "North America",
    },
    {
        countryName: "Guam",
        capitalName: "Hagatna",
        capitalLatitude: "13,46666667",
        capitalLongitude: "144,733333",
        countryCode: "GU",
        continentName: "Australia",
    },
    {
        countryName: "Guatemala",
        capitalName: "Guatemala City",
        capitalLatitude: "14,61666667",
        capitalLongitude: "-90,516667",
        countryCode: "GT",
        continentName: "Central America",
    },
    {
        countryName: "Guernsey",
        capitalName: "Saint Peter Port",
        capitalLatitude: "49,45",
        capitalLongitude: "-2,533333",
        countryCode: "GG",
        continentName: "Europe",
    },
    {
        countryName: "Guinea",
        capitalName: "Conakry",
        capitalLatitude: "9,5",
        capitalLongitude: "-13,7",
        countryCode: "GN",
        continentName: "Africa",
    },
    {
        countryName: "Guinea-Bissau",
        capitalName: "Bissau",
        capitalLatitude: "11,85",
        capitalLongitude: "-15,583333",
        countryCode: "GW",
        continentName: "Africa",
    },
    {
        countryName: "Guyana",
        capitalName: "Georgetown",
        capitalLatitude: "6,8",
        capitalLongitude: "-58,15",
        countryCode: "GY",
        continentName: "South America",
    },
    {
        countryName: "Haiti",
        capitalName: "Port-au-Prince",
        capitalLatitude: "18,53333333",
        capitalLongitude: "-72,333333",
        countryCode: "HT",
        continentName: "North America",
    },
    {
        countryName: "Honduras",
        capitalName: "Tegucigalpa",
        capitalLatitude: "14,1",
        capitalLongitude: "-87,216667",
        countryCode: "HN",
        continentName: "Central America",
    },
    {
        countryName: "Hong Kong",
        capitalName: "Hong Kong",
        capitalLatitude: "22,310978",
        capitalLongitude: "114,172209",
        countryCode: "HK",
        continentName: "Asia",
    },
    {
        countryName: "Hungary",
        capitalName: "Budapest",
        capitalLatitude: "47,5",
        capitalLongitude: "19,083333",
        countryCode: "HU",
        continentName: "Europe",
    },
    {
        countryName: "Iceland",
        capitalName: "Reykjavik",
        capitalLatitude: "64,15",
        capitalLongitude: "-21,95",
        countryCode: "IS",
        continentName: "Europe",
    },
    {
        countryName: "India",
        capitalName: "New Delhi",
        capitalLatitude: "28,6",
        capitalLongitude: "77,2",
        countryCode: "IN",
        continentName: "Asia",
    },
    {
        countryName: "Indonesia",
        capitalName: "Jakarta",
        capitalLatitude: "-6,166666667",
        capitalLongitude: "106,816667",
        countryCode: "ID",
        continentName: "Asia",
    },
    {
        countryName: "Iran",
        capitalName: "Tehran",
        capitalLatitude: "35,7",
        capitalLongitude: "51,416667",
        countryCode: "IR",
        continentName: "Asia",
    },
    {
        countryName: "Iraq",
        capitalName: "Baghdad",
        capitalLatitude: "33,33333333",
        capitalLongitude: "44,4",
        countryCode: "IQ",
        continentName: "Asia",
    },
    {
        countryName: "Ireland",
        capitalName: "Dublin",
        capitalLatitude: "53,31666667",
        capitalLongitude: "-6,233333",
        countryCode: "IE",
        continentName: "Europe",
    },
    {
        countryName: "Isle of Man",
        capitalName: "Douglas",
        capitalLatitude: "54,15",
        capitalLongitude: "-4,483333",
        countryCode: "IM",
        continentName: "Europe",
    },
    {
        countryName: "Israel",
        capitalName: "Jerusalem",
        capitalLatitude: "31,76666667",
        capitalLongitude: "35,233333",
        countryCode: "IL",
        continentName: "Asia",
    },
    {
        countryName: "Italy",
        capitalName: "Rome",
        capitalLatitude: "41,9",
        capitalLongitude: "12,483333",
        countryCode: "IT",
        continentName: "Europe",
    },
    {
        countryName: "Jamaica",
        capitalName: "Kingston",
        capitalLatitude: "18",
        capitalLongitude: "-76,8",
        countryCode: "JM",
        continentName: "North America",
    },
    {
        countryName: "Japan",
        capitalName: "Tokyo",
        capitalLatitude: "35,68333333",
        capitalLongitude: "139,75",
        countryCode: "JP",
        continentName: "Asia",
    },
    {
        countryName: "Jersey",
        capitalName: "Saint Helier",
        capitalLatitude: "49,18333333",
        capitalLongitude: "-2,1",
        countryCode: "JE",
        continentName: "Europe",
    },
    {
        countryName: "Jordan",
        capitalName: "Amman",
        capitalLatitude: "31,95",
        capitalLongitude: "35,933333",
        countryCode: "JO",
        continentName: "Asia",
    },
    {
        countryName: "Kazakhstan",
        capitalName: "Astana",
        capitalLatitude: "51,16666667",
        capitalLongitude: "71,416667",
        countryCode: "KZ",
        continentName: "Asia",
    },
    {
        countryName: "Kenya",
        capitalName: "Nairobi",
        capitalLatitude: "-1,283333333",
        capitalLongitude: "36,816667",
        countryCode: "KE",
        continentName: "Africa",
    },
    {
        countryName: "Kiribati",
        capitalName: "Tarawa",
        capitalLatitude: "-0,883333333",
        capitalLongitude: "169,533333",
        countryCode: "KI",
        continentName: "Australia",
    },
    {
        countryName: "Kosovo",
        capitalName: "Pristina",
        capitalLatitude: "42,66666667",
        capitalLongitude: "21,166667",
        countryCode: "KO",
        continentName: "Europe",
    },
    {
        countryName: "Kuwait",
        capitalName: "Kuwait City",
        capitalLatitude: "29,36666667",
        capitalLongitude: "47,966667",
        countryCode: "KW",
        continentName: "Asia",
    },
    {
        countryName: "Kyrgyzstan",
        capitalName: "Bishkek",
        capitalLatitude: "42,86666667",
        capitalLongitude: "74,6",
        countryCode: "KG",
        continentName: "Asia",
    },
    {
        countryName: "Laos",
        capitalName: "Vientiane",
        capitalLatitude: "17,96666667",
        capitalLongitude: "102,6",
        countryCode: "LA",
        continentName: "Asia",
    },
    {
        countryName: "Latvia",
        capitalName: "Riga",
        capitalLatitude: "56,95",
        capitalLongitude: "24,1",
        countryCode: "LV",
        continentName: "Europe",
    },
    {
        countryName: "Lebanon",
        capitalName: "Beirut",
        capitalLatitude: "33,86666667",
        capitalLongitude: "35,5",
        countryCode: "LB",
        continentName: "Asia",
    },
    {
        countryName: "Lesotho",
        capitalName: "Maseru",
        capitalLatitude: "-29,31666667",
        capitalLongitude: "27,483333",
        countryCode: "LS",
        continentName: "Africa",
    },
    {
        countryName: "Liberia",
        capitalName: "Monrovia",
        capitalLatitude: "6,3",
        capitalLongitude: "-10,8",
        countryCode: "LR",
        continentName: "Africa",
    },
    {
        countryName: "Libya",
        capitalName: "Tripoli",
        capitalLatitude: "32,88333333",
        capitalLongitude: "13,166667",
        countryCode: "LY",
        continentName: "Africa",
    },
    {
        countryName: "Liechtenstein",
        capitalName: "Vaduz",
        capitalLatitude: "47,13333333",
        capitalLongitude: "9,516667",
        countryCode: "LI",
        continentName: "Europe",
    },
    {
        countryName: "Lithuania",
        capitalName: "Vilnius",
        capitalLatitude: "54,68333333",
        capitalLongitude: "25,316667",
        countryCode: "LT",
        continentName: "Europe",
    },
    {
        countryName: "Luxembourg",
        capitalName: "Luxembourg",
        capitalLatitude: "49,6",
        capitalLongitude: "6,116667",
        countryCode: "LU",
        continentName: "Europe",
    },
    {
        countryName: "Macau",
        capitalName: "Macau",
        capitalLatitude: "22,195854",
        capitalLongitude: "113,543597",
        countryCode: "MO",
        continentName: "Asia",
    },
    {
        countryName: "Macedonia",
        capitalName: "Skopje",
        capitalLatitude: "42",
        capitalLongitude: "21,433333",
        countryCode: "MK",
        continentName: "Europe",
    },
    {
        countryName: "Madagascar",
        capitalName: "Antananarivo",
        capitalLatitude: "-18,91666667",
        capitalLongitude: "47,516667",
        countryCode: "MG",
        continentName: "Africa",
    },
    {
        countryName: "Malawi",
        capitalName: "Lilongwe",
        capitalLatitude: "-13,96666667",
        capitalLongitude: "33,783333",
        countryCode: "MW",
        continentName: "Africa",
    },
    {
        countryName: "Malaysia",
        capitalName: "Kuala Lumpur",
        capitalLatitude: "3,166666667",
        capitalLongitude: "101,7",
        countryCode: "MY",
        continentName: "Asia",
    },
    {
        countryName: "Maldives",
        capitalName: "Male",
        capitalLatitude: "4,166666667",
        capitalLongitude: "73,5",
        countryCode: "MV",
        continentName: "Asia",
    },
    {
        countryName: "Mali",
        capitalName: "Bamako",
        capitalLatitude: "12,65",
        capitalLongitude: "-8",
        countryCode: "ML",
        continentName: "Africa",
    },
    {
        countryName: "Malta",
        capitalName: "Valletta",
        capitalLatitude: "35,88333333",
        capitalLongitude: "14,5",
        countryCode: "MT",
        continentName: "Europe",
    },
    {
        countryName: "Marshall Islands",
        capitalName: "Majuro",
        capitalLatitude: "7,1",
        capitalLongitude: "171,383333",
        countryCode: "MH",
        continentName: "Australia",
    },
    {
        countryName: "Mauritania",
        capitalName: "Nouakchott",
        capitalLatitude: "18,06666667",
        capitalLongitude: "-15,966667",
        countryCode: "MR",
        continentName: "Africa",
    },
    {
        countryName: "Mauritius",
        capitalName: "Port Louis",
        capitalLatitude: "-20,15",
        capitalLongitude: "57,483333",
        countryCode: "MU",
        continentName: "Africa",
    },
    {
        countryName: "Mexico",
        capitalName: "Mexico City",
        capitalLatitude: "19,43333333",
        capitalLongitude: "-99,133333",
        countryCode: "MX",
        continentName: "Central America",
    },
    {
        countryName: "Moldova",
        capitalName: "Chisinau",
        capitalLatitude: "47",
        capitalLongitude: "28,85",
        countryCode: "MD",
        continentName: "Europe",
    },
    {
        countryName: "Monaco",
        capitalName: "Monaco",
        capitalLatitude: "43,73333333",
        capitalLongitude: "7,416667",
        countryCode: "MC",
        continentName: "Europe",
    },
    {
        countryName: "Mongolia",
        capitalName: "Ulaanbaatar",
        capitalLatitude: "47,91666667",
        capitalLongitude: "106,916667",
        countryCode: "MN",
        continentName: "Asia",
    },
    {
        countryName: "Montenegro",
        capitalName: "Podgorica",
        capitalLatitude: "42,43333333",
        capitalLongitude: "19,266667",
        countryCode: "ME",
        continentName: "Europe",
    },
    {
        countryName: "Montserrat",
        capitalName: "Plymouth",
        capitalLatitude: "16,7",
        capitalLongitude: "-62,216667",
        countryCode: "MS",
        continentName: "North America",
    },
    {
        countryName: "Morocco",
        capitalName: "Rabat",
        capitalLatitude: "34,01666667",
        capitalLongitude: "-6,816667",
        countryCode: "MA",
        continentName: "Africa",
    },
    {
        countryName: "Mozambique",
        capitalName: "Maputo",
        capitalLatitude: "-25,95",
        capitalLongitude: "32,583333",
        countryCode: "MZ",
        continentName: "Africa",
    },
    {
        countryName: "Myanmar",
        capitalName: "Rangoon",
        capitalLatitude: "16,8",
        capitalLongitude: "96,15",
        countryCode: "MM",
        continentName: "Asia",
    },
    {
        countryName: "Namibia",
        capitalName: "Windhoek",
        capitalLatitude: "-22,56666667",
        capitalLongitude: "17,083333",
        countryCode: "NA",
        continentName: "Africa",
    },
    {
        countryName: "Nauru",
        capitalName: "Yaren",
        capitalLatitude: "-0,5477",
        capitalLongitude: "166,920867",
        countryCode: "NR",
        continentName: "Australia",
    },
    {
        countryName: "Nepal",
        capitalName: "Kathmandu",
        capitalLatitude: "27,71666667",
        capitalLongitude: "85,316667",
        countryCode: "NP",
        continentName: "Asia",
    },
    {
        countryName: "Netherlands",
        capitalName: "Amsterdam",
        capitalLatitude: "52,35",
        capitalLongitude: "4,916667",
        countryCode: "NL",
        continentName: "Europe",
    },
    {
        countryName: "New Caledonia",
        capitalName: "Noumea",
        capitalLatitude: "-22,26666667",
        capitalLongitude: "166,45",
        countryCode: "NC",
        continentName: "Australia",
    },
    {
        countryName: "New Zealand",
        capitalName: "Wellington",
        capitalLatitude: "-41,3",
        capitalLongitude: "174,783333",
        countryCode: "NZ",
        continentName: "Australia",
    },
    {
        countryName: "Nicaragua",
        capitalName: "Managua",
        capitalLatitude: "12,13333333",
        capitalLongitude: "-86,25",
        countryCode: "NI",
        continentName: "Central America",
    },
    {
        countryName: "Niger",
        capitalName: "Niamey",
        capitalLatitude: "13,51666667",
        capitalLongitude: "2,116667",
        countryCode: "NE",
        continentName: "Africa",
    },
    {
        countryName: "Nigeria",
        capitalName: "Abuja",
        capitalLatitude: "9,083333333",
        capitalLongitude: "7,533333",
        countryCode: "NG",
        continentName: "Africa",
    },
    {
        countryName: "Niue",
        capitalName: "Alofi",
        capitalLatitude: "-19,01666667",
        capitalLongitude: "-169,916667",
        countryCode: "NU",
        continentName: "Australia",
    },
    {
        countryName: "Norfolk Island",
        capitalName: "Kingston",
        capitalLatitude: "-29,05",
        capitalLongitude: "167,966667",
        countryCode: "NF",
        continentName: "Australia",
    },
    {
        countryName: "North Korea",
        capitalName: "Pyongyang",
        capitalLatitude: "39,01666667",
        capitalLongitude: "125,75",
        countryCode: "KP",
        continentName: "Asia",
    },
    {
        countryName: "Northern Cyprus",
        capitalName: "North Nicosia",
        capitalLatitude: "35,183333",
        capitalLongitude: "33,366667",
        countryCode: "NULL",
        continentName: "Europe",
    },
    {
        countryName: "Northern Mariana Islands",
        capitalName: "Saipan",
        capitalLatitude: "15,2",
        capitalLongitude: "145,75",
        countryCode: "MP",
        continentName: "Australia",
    },
    {
        countryName: "Norway",
        capitalName: "Oslo",
        capitalLatitude: "59,91666667",
        capitalLongitude: "10,75",
        countryCode: "NO",
        continentName: "Europe",
    },
    {
        countryName: "Oman",
        capitalName: "Muscat",
        capitalLatitude: "23,61666667",
        capitalLongitude: "58,583333",
        countryCode: "OM",
        continentName: "Asia",
    },
    {
        countryName: "Pakistan",
        capitalName: "Islamabad",
        capitalLatitude: "33,68333333",
        capitalLongitude: "73,05",
        countryCode: "PK",
        continentName: "Asia",
    },
    {
        countryName: "Palau",
        capitalName: "Melekeok",
        capitalLatitude: "7,483333333",
        capitalLongitude: "134,633333",
        countryCode: "PW",
        continentName: "Australia",
    },
    {
        countryName: "Palestine",
        capitalName: "Jerusalem",
        capitalLatitude: "31,76666667",
        capitalLongitude: "35,233333",
        countryCode: "PS",
        continentName: "Asia",
    },
    {
        countryName: "Panama",
        capitalName: "Panama City",
        capitalLatitude: "8,966666667",
        capitalLongitude: "-79,533333",
        countryCode: "PA",
        continentName: "Central America",
    },
    {
        countryName: "Papua New Guinea",
        capitalName: "Port Moresby",
        capitalLatitude: "-9,45",
        capitalLongitude: "147,183333",
        countryCode: "PG",
        continentName: "Australia",
    },
    {
        countryName: "Paraguay",
        capitalName: "Asuncion",
        capitalLatitude: "-25,26666667",
        capitalLongitude: "-57,666667",
        countryCode: "PY",
        continentName: "South America",
    },
    {
        countryName: "Peru",
        capitalName: "Lima",
        capitalLatitude: "-12,05",
        capitalLongitude: "-77,05",
        countryCode: "PE",
        continentName: "South America",
    },
    {
        countryName: "Philippines",
        capitalName: "Manila",
        capitalLatitude: "14,6",
        capitalLongitude: "120,966667",
        countryCode: "PH",
        continentName: "Asia",
    },
    {
        countryName: "Pitcairn Islands",
        capitalName: "Adamstown",
        capitalLatitude: "-25,06666667",
        capitalLongitude: "-130,083333",
        countryCode: "PN",
        continentName: "Australia",
    },
    {
        countryName: "Poland",
        capitalName: "Warsaw",
        capitalLatitude: "52,25",
        capitalLongitude: "21",
        countryCode: "PL",
        continentName: "Europe",
    },
    {
        countryName: "Portugal",
        capitalName: "Lisbon",
        capitalLatitude: "38,71666667",
        capitalLongitude: "-9,133333",
        countryCode: "PT",
        continentName: "Europe",
    },
    {
        countryName: "Puerto Rico",
        capitalName: "San Juan",
        capitalLatitude: "18,46666667",
        capitalLongitude: "-66,116667",
        countryCode: "PR",
        continentName: "North America",
    },
    {
        countryName: "Qatar",
        capitalName: "Doha",
        capitalLatitude: "25,28333333",
        capitalLongitude: "51,533333",
        countryCode: "QA",
        continentName: "Asia",
    },
    {
        countryName: "Republic of Congo",
        capitalName: "Brazzaville",
        capitalLatitude: "-4,25",
        capitalLongitude: "15,283333",
        countryCode: "CG",
        continentName: "Africa",
    },
    {
        countryName: "Romania",
        capitalName: "Bucharest",
        capitalLatitude: "44,43333333",
        capitalLongitude: "26,1",
        countryCode: "RO",
        continentName: "Europe",
    },
    {
        countryName: "Russia",
        capitalName: "Moscow",
        capitalLatitude: "55,75",
        capitalLongitude: "37,6",
        countryCode: "RU",
        continentName: "Europe",
    },
    {
        countryName: "Rwanda",
        capitalName: "Kigali",
        capitalLatitude: "-1,95",
        capitalLongitude: "30,05",
        countryCode: "RW",
        continentName: "Africa",
    },
    {
        countryName: "Saint Barthelemy",
        capitalName: "Gustavia",
        capitalLatitude: "17,88333333",
        capitalLongitude: "-62,85",
        countryCode: "BL",
        continentName: "North America",
    },
    {
        countryName: "Saint Helena",
        capitalName: "Jamestown",
        capitalLatitude: "-15,93333333",
        capitalLongitude: "-5,716667",
        countryCode: "SH",
        continentName: "Africa",
    },
    {
        countryName: "Saint Kitts and Nevis",
        capitalName: "Basseterre",
        capitalLatitude: "17,3",
        capitalLongitude: "-62,716667",
        countryCode: "KN",
        continentName: "North America",
    },
    {
        countryName: "Saint Lucia",
        capitalName: "Castries",
        capitalLatitude: "14",
        capitalLongitude: "-61",
        countryCode: "LC",
        continentName: "North America",
    },
    {
        countryName: "Saint Martin",
        capitalName: "Marigot",
        capitalLatitude: "18,0731",
        capitalLongitude: "-63,0822",
        countryCode: "MF",
        continentName: "North America",
    },
    {
        countryName: "Saint Pierre and Miquelon",
        capitalName: "Saint-Pierre",
        capitalLatitude: "46,76666667",
        capitalLongitude: "-56,183333",
        countryCode: "PM",
        continentName: "Central America",
    },
    {
        countryName: "Saint Vincent and the Grenadines",
        capitalName: "Kingstown",
        capitalLatitude: "13,13333333",
        capitalLongitude: "-61,216667",
        countryCode: "VC",
        continentName: "Central America",
    },
    {
        countryName: "Samoa",
        capitalName: "Apia",
        capitalLatitude: "-13,81666667",
        capitalLongitude: "-171,766667",
        countryCode: "WS",
        continentName: "Australia",
    },
    {
        countryName: "San Marino",
        capitalName: "San Marino",
        capitalLatitude: "43,93333333",
        capitalLongitude: "12,416667",
        countryCode: "SM",
        continentName: "Europe",
    },
    {
        countryName: "Sao Tome and Principe",
        capitalName: "Sao Tome",
        capitalLatitude: "0,333333333",
        capitalLongitude: "6,733333",
        countryCode: "ST",
        continentName: "Africa",
    },
    {
        countryName: "Saudi Arabia",
        capitalName: "Riyadh",
        capitalLatitude: "24,65",
        capitalLongitude: "46,7",
        countryCode: "SA",
        continentName: "Asia",
    },
    {
        countryName: "Senegal",
        capitalName: "Dakar",
        capitalLatitude: "14,73333333",
        capitalLongitude: "-17,633333",
        countryCode: "SN",
        continentName: "Africa",
    },
    {
        countryName: "Serbia",
        capitalName: "Belgrade",
        capitalLatitude: "44,83333333",
        capitalLongitude: "20,5",
        countryCode: "RS",
        continentName: "Europe",
    },
    {
        countryName: "Seychelles",
        capitalName: "Victoria",
        capitalLatitude: "-4,616666667",
        capitalLongitude: "55,45",
        countryCode: "SC",
        continentName: "Africa",
    },
    {
        countryName: "Sierra Leone",
        capitalName: "Freetown",
        capitalLatitude: "8,483333333",
        capitalLongitude: "-13,233333",
        countryCode: "SL",
        continentName: "Africa",
    },
    {
        countryName: "Singapore",
        capitalName: "Singapore",
        capitalLatitude: "1,283333333",
        capitalLongitude: "103,85",
        countryCode: "SG",
        continentName: "Asia",
    },
    {
        countryName: "Sint Maarten",
        capitalName: "Philipsburg",
        capitalLatitude: "18,01666667",
        capitalLongitude: "-63,033333",
        countryCode: "SX",
        continentName: "North America",
    },
    {
        countryName: "Slovakia",
        capitalName: "Bratislava",
        capitalLatitude: "48,15",
        capitalLongitude: "17,116667",
        countryCode: "SK",
        continentName: "Europe",
    },
    {
        countryName: "Slovenia",
        capitalName: "Ljubljana",
        capitalLatitude: "46,05",
        capitalLongitude: "14,516667",
        countryCode: "SI",
        continentName: "Europe",
    },
    {
        countryName: "Solomon Islands",
        capitalName: "Honiara",
        capitalLatitude: "-9,433333333",
        capitalLongitude: "159,95",
        countryCode: "SB",
        continentName: "Australia",
    },
    {
        countryName: "Somalia",
        capitalName: "Mogadishu",
        capitalLatitude: "2,066666667",
        capitalLongitude: "45,333333",
        countryCode: "SO",
        continentName: "Africa",
    },
    {
        countryName: "Somaliland",
        capitalName: "Hargeisa",
        capitalLatitude: "9,55",
        capitalLongitude: "44,05",
        countryCode: "NULL",
        continentName: "Africa",
    },
    {
        countryName: "South Africa",
        capitalName: "Pretoria",
        capitalLatitude: "-25,7",
        capitalLongitude: "28,216667",
        countryCode: "ZA",
        continentName: "Africa",
    },
    {
        countryName: "South Georgia and South Sandwich Islands",
        capitalName: "King Edward Point",
        capitalLatitude: "-54,283333",
        capitalLongitude: "-36,5",
        countryCode: "GS",
        continentName: "Antarctica",
    },
    {
        countryName: "South Korea",
        capitalName: "Seoul",
        capitalLatitude: "37,55",
        capitalLongitude: "126,983333",
        countryCode: "KR",
        continentName: "Asia",
    },
    {
        countryName: "South Sudan",
        capitalName: "Juba",
        capitalLatitude: "4,85",
        capitalLongitude: "31,616667",
        countryCode: "SS",
        continentName: "Africa",
    },
    {
        countryName: "Spain",
        capitalName: "Madrid",
        capitalLatitude: "40,4",
        capitalLongitude: "-3,683333",
        countryCode: "ES",
        continentName: "Europe",
    },
    {
        countryName: "Sri Lanka",
        capitalName: "Colombo",
        capitalLatitude: "6,916666667",
        capitalLongitude: "79,833333",
        countryCode: "LK",
        continentName: "Asia",
    },
    {
        countryName: "Sudan",
        capitalName: "Khartoum",
        capitalLatitude: "15,6",
        capitalLongitude: "32,533333",
        countryCode: "SD",
        continentName: "Africa",
    },
    {
        countryName: "Suriname",
        capitalName: "Paramaribo",
        capitalLatitude: "5,833333333",
        capitalLongitude: "-55,166667",
        countryCode: "SR",
        continentName: "South America",
    },
    {
        countryName: "Svalbard",
        capitalName: "Longyearbyen",
        capitalLatitude: "78,21666667",
        capitalLongitude: "15,633333",
        countryCode: "SJ",
        continentName: "Europe",
    },
    {
        countryName: "Swaziland",
        capitalName: "Mbabane",
        capitalLatitude: "-26,31666667",
        capitalLongitude: "31,133333",
        countryCode: "SZ",
        continentName: "Africa",
    },
    {
        countryName: "Sweden",
        capitalName: "Stockholm",
        capitalLatitude: "59,33333333",
        capitalLongitude: "18,05",
        countryCode: "SE",
        continentName: "Europe",
    },
    {
        countryName: "Switzerland",
        capitalName: "Bern",
        capitalLatitude: "46,91666667",
        capitalLongitude: "7,466667",
        countryCode: "CH",
        continentName: "Europe",
    },
    {
        countryName: "Syria",
        capitalName: "Damascus",
        capitalLatitude: "33,5",
        capitalLongitude: "36,3",
        countryCode: "SY",
        continentName: "Asia",
    },
    {
        countryName: "Taiwan",
        capitalName: "Taipei",
        capitalLatitude: "25,03333333",
        capitalLongitude: "121,516667",
        countryCode: "TW",
        continentName: "Asia",
    },
    {
        countryName: "Tajikistan",
        capitalName: "Dushanbe",
        capitalLatitude: "38,55",
        capitalLongitude: "68,766667",
        countryCode: "TJ",
        continentName: "Asia",
    },
    {
        countryName: "Tanzania",
        capitalName: "Dar es Salaam",
        capitalLatitude: "-6,8",
        capitalLongitude: "39,283333",
        countryCode: "TZ",
        continentName: "Africa",
    },
    {
        countryName: "Thailand",
        capitalName: "Bangkok",
        capitalLatitude: "13,75",
        capitalLongitude: "100,516667",
        countryCode: "TH",
        continentName: "Asia",
    },
    {
        countryName: "The Gambia",
        capitalName: "Banjul",
        capitalLatitude: "13,45",
        capitalLongitude: "-16,566667",
        countryCode: "GM",
        continentName: "Africa",
    },
    {
        countryName: "Timor-Leste",
        capitalName: "Dili",
        capitalLatitude: "-8,583333333",
        capitalLongitude: "125,6",
        countryCode: "TL",
        continentName: "Asia",
    },
    {
        countryName: "Togo",
        capitalName: "Lome",
        capitalLatitude: "6,116666667",
        capitalLongitude: "1,216667",
        countryCode: "TG",
        continentName: "Africa",
    },
    {
        countryName: "Tokelau",
        capitalName: "Atafu",
        capitalLatitude: "-9,166667",
        capitalLongitude: "-171,833333",
        countryCode: "TK",
        continentName: "Australia",
    },
    {
        countryName: "Tonga",
        capitalName: "Nuku alofa",
        capitalLatitude: "-21,13333333",
        capitalLongitude: "-175,2",
        countryCode: "TO",
        continentName: "Australia",
    },
    {
        countryName: "Trinidad and Tobago",
        capitalName: "Port of Spain",
        capitalLatitude: "10,65",
        capitalLongitude: "-61,516667",
        countryCode: "TT",
        continentName: "North America",
    },
    {
        countryName: "Tunisia",
        capitalName: "Tunis",
        capitalLatitude: "36,8",
        capitalLongitude: "10,183333",
        countryCode: "TN",
        continentName: "Africa",
    },
    {
        countryName: "Turkey",
        capitalName: "Ankara",
        capitalLatitude: "39,93333333",
        capitalLongitude: "32,866667",
        countryCode: "TR",
        continentName: "Europe",
    },
    {
        countryName: "Turkmenistan",
        capitalName: "Ashgabat",
        capitalLatitude: "37,95",
        capitalLongitude: "58,383333",
        countryCode: "TM",
        continentName: "Asia",
    },
    {
        countryName: "Turks and Caicos Islands",
        capitalName: "Grand Turk",
        capitalLatitude: "21,46666667",
        capitalLongitude: "-71,133333",
        countryCode: "TC",
        continentName: "North America",
    },
    {
        countryName: "Tuvalu",
        capitalName: "Funafuti",
        capitalLatitude: "-8,516666667",
        capitalLongitude: "179,216667",
        countryCode: "TV",
        continentName: "Australia",
    },
    {
        countryName: "Uganda",
        capitalName: "Kampala",
        capitalLatitude: "0,316666667",
        capitalLongitude: "32,55",
        countryCode: "UG",
        continentName: "Africa",
    },
    {
        countryName: "Ukraine",
        capitalName: "Kyiv",
        capitalLatitude: "50,43333333",
        capitalLongitude: "30,516667",
        countryCode: "UA",
        continentName: "Europe",
    },
    {
        countryName: "United Arab Emirates",
        capitalName: "Abu Dhabi",
        capitalLatitude: "24,46666667",
        capitalLongitude: "54,366667",
        countryCode: "AE",
        continentName: "Asia",
    },
    {
        countryName: "United Kingdom",
        capitalName: "London",
        capitalLatitude: "51,5",
        capitalLongitude: "-0,083333",
        countryCode: "GB",
        continentName: "Europe",
    },
    {
        countryName: "United States",
        capitalName: "Washington, D,C,",
        capitalLatitude: "38,883333",
        capitalLongitude: "-77",
        countryCode: "US",
        continentName: "Central America",
    },
    {
        countryName: "Uruguay",
        capitalName: "Montevideo",
        capitalLatitude: "-34,85",
        capitalLongitude: "-56,166667",
        countryCode: "UY",
        continentName: "South America",
    },
    {
        countryName: "US Minor Outlying Islands",
        capitalName: "Washington, D,C,",
        capitalLatitude: "38,883333",
        capitalLongitude: "-77",
        countryCode: "UM",
        continentName: "Australia",
    },
    {
        countryName: "US Virgin Islands",
        capitalName: "Charlotte Amalie",
        capitalLatitude: "18,35",
        capitalLongitude: "-64,933333",
        countryCode: "VI",
        continentName: "North America",
    },
    {
        countryName: "Uzbekistan",
        capitalName: "Tashkent",
        capitalLatitude: "41,31666667",
        capitalLongitude: "69,25",
        countryCode: "UZ",
        continentName: "Asia",
    },
    {
        countryName: "Vanuatu",
        capitalName: "Port-Vila",
        capitalLatitude: "-17,73333333",
        capitalLongitude: "168,316667",
        countryCode: "VU",
        continentName: "Australia",
    },
    {
        countryName: "Vatican City",
        capitalName: "Vatican City",
        capitalLatitude: "41,9",
        capitalLongitude: "12,45",
        countryCode: "VA",
        continentName: "Europe",
    },
    {
        countryName: "Venezuela",
        capitalName: "Caracas",
        capitalLatitude: "10,48333333",
        capitalLongitude: "-66,866667",
        countryCode: "VE",
        continentName: "South America",
    },
    {
        countryName: "Vietnam",
        capitalName: "Hanoi",
        capitalLatitude: "21,03333333",
        capitalLongitude: "105,85",
        countryCode: "VN",
        continentName: "Asia",
    },
    {
        countryName: "Wallis and Futuna",
        capitalName: "Mata-Utu",
        capitalLatitude: "-13,95",
        capitalLongitude: "-171,933333",
        countryCode: "WF",
        continentName: "Australia",
    },
    {
        countryName: "Western Sahara",
        capitalName: "El-Aaiún",
        capitalLatitude: "27,153611",
        capitalLongitude: "-13,203333",
        countryCode: "EH",
        continentName: "Africa",
    },
    {
        countryName: "Yemen",
        capitalName: "Sanaa",
        capitalLatitude: "15,35",
        capitalLongitude: "44,2",
        countryCode: "YE",
        continentName: "Asia",
    },
    {
        countryName: "Zambia",
        capitalName: "Lusaka",
        capitalLatitude: "-15,41666667",
        capitalLongitude: "28,283333",
        countryCode: "ZM",
        continentName: "Africa",
    },
    {
        countryName: "Zimbabwe",
        capitalName: "Harare",
        capitalLatitude: "-17,81666667",
        capitalLongitude: "31,033333",
        countryCode: "ZW",
        continentName: "Africa",
    },
];
